name: Play Chess

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  update-board:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Play Chess
        uses: marcizhu/readme-chess@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
